name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' ||
        (github.event_name == 'pull_request' && github.event.action != 'closed')
    environment: pr
    runs-on: ubuntu-latest

    # ────────────────────────────────────────────────────────────────────────────
    # 모든 빌드 · 런타임 환경 변수를 이 env 블록에 등록하세요
    env:
      STRIPE_SECRET_KEY:                      ${{ secrets.STRIPE_SECRET_KEY }}
      SQUARE_ACCESS_TOKEN:                    ${{ secrets.SQUARE_ACCESS_TOKEN }}
      SQUARE_LOCATION_ID:                     ${{ secrets.SQUARE_LOCATION_ID }}
      NODE_ENV:                               development

      NEXT_PUBLIC_FIREBASE_API_KEY:           ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:       ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID:        ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:    ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID:            ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:    ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}

      FIREBASE_PRIVATE_KEY:                   ${{ secrets.FIREBASE_PRIVATE_KEY }}
      NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL:      ${{ secrets.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL }}

      AZURE_STORAGE_CONNECTION_STRING:        ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
    # ────────────────────────────────────────────────────────────────────────────

    name: Build and Deploy Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_ROCK_04D45050F }}
          repo_token:                         ${{ secrets.GITHUB_TOKEN }}
          action:                             "upload"

          # Next.js SSR/ISR 배포 설정
          app_location:      "app"
          app_build_command: "npm ci && npm run build"
          output_location:   ""
          api_location:      ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    environment: pr
    runs-on: ubuntu-latest

    # (필요하다면 동일한 env: 블록을 추가하실 수 있습니다)
    env:
      STRIPE_SECRET_KEY:       ${{ secrets.STRIPE_SECRET_KEY }}
      SQUARE_ACCESS_TOKEN:     ${{ secrets.SQUARE_ACCESS_TOKEN }}
      SQUARE_LOCATION_ID:      ${{ secrets.SQUARE_LOCATION_ID }}
      NODE_ENV:                development
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      NEXT_PUBLIC_FIREBASE_API_KEY:    ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID:  ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:    ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID:      ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
      FIREBASE_PRIVATE_KEY:             ${{ secrets.FIREBASE_PRIVATE_KEY }}
      NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL: ${{ secrets.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL }}

    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_ROCK_04D45050F }}
          action:                          "close"
