name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' ||
        (github.event_name == 'pull_request' && github.event.action != 'closed')
    environment: pr
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # PR 전용 Environment 에 저장된 토큰
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_ROCK_04D45050F }}
          # GitHub API 호출용 토큰 (자동 제공)
          repo_token:                         ${{ secrets.GITHUB_TOKEN }}
          action:                             "upload"

          # ─────────────────────────────────────────────────────
          # Next.js SSR/ISR 배포 설정
          app_location:      "app"                    # Next.js 프로젝트 루트
          app_build_command: "npm ci && npm run build" # Next.js 빌드 커맨드
          output_location:   ""                       # 비워두면 Oryx가 .next 폴더와 API 라우트를 자동 감지
          api_location:      ""                       # Next.js API routes 는 pages/api 아래에 자동 배포
          # ─────────────────────────────────────────────────────

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    environment: pr
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_ROCK_04D45050F }}
          action:                          "close"
