name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' ||
        (github.event_name == 'pull_request' && github.event.action != 'closed')
    environment: pr
    runs-on: ubuntu-latest

    env:
      # Only build‐time secrets here (e.g. your Firebase service account JSON)
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & Deploy Next.js to Azure Static Web Apps
        id: swadeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_ROCK_04D45050F }}
          repo_token:                         ${{ secrets.GITHUB_TOKEN }}
          action:                             upload

          # ─────────── Next.js build settings ───────────
          app_location:      "app"                         # where your Next.js lives
          app_build_command: "npm ci && npm run build"     # ensure you actually build
          output_location:   "app/.next"                   # point to the .next folder
          api_location:      ""                            # leave blank for pages/api
          # ────────────────────────────────────────────────

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    environment: pr
    runs-on: ubuntu-latest

    steps:
      - name: Close SWA PR
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_ROCK_04D45050F }}
          action:                          close
