name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' ||
        (github.event_name == 'pull_request' && github.event.action != 'closed')
    environment: pr
    runs-on: ubuntu-latest

    # ────────────────────────────────────────────────────────────────
    # ONLY the vars your build needs go here (e.g. service-account JSON).
    # Everything else (public NEXT_PUBLIC_*, runtime-only secrets)
    # should live in Azure Static Web App → Configuration → Application settings.
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    # ────────────────────────────────────────────────────────────────

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & deploy to Static Web Apps
        id: swadeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_ROCK_04D45050F }}
          repo_token:                         ${{ secrets.GITHUB_TOKEN }}
          action:                             upload

          # ─────────────────────────────────────────────
          app_location:    app      # <-- your Next.js folder
          api_location:          "" # <-- leave blank for pages/api
          output_location:       "" # <-- let Oryx detect .next + SSR
          # ─────────────────────────────────────────────

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    environment: pr
    runs-on: ubuntu-latest

    steps:
      - name: Close SWA PR
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_ROCK_04D45050F }}
          action:                          close
